package com.bjj.videorec.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Entity
@Table(name = "video_tags")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class VideoTag {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "tag_name", nullable = false, length = 2000)
    private String tagName;

    @Column(name = "confidence")
    private Float confidence;

    @Enumerated(EnumType.STRING)
    @Column(name = "source", nullable = false)
    private TagSource source;

    @Column(name = "timestamp_seconds")
    private Float timestampSeconds;

    @Column(name = "created_date", nullable = false)
    private LocalDateTime createdDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "video_id", nullable = false)
    @JsonIgnore
    private Video video;

    @PrePersist
    protected void onCreate() {
        createdDate = LocalDateTime.now();
    }

    public enum TagSource {
        AUTO, // Generated by Google Cloud Video Intelligence
        MANUAL // Added by user
    }
}
